[package]
name = "ibc-prost-compiler"
version = "0.1.0"
authors = ["Greg Szabo <greg@philosobear.com>"]
edition = "2018"

[dependencies]
walkdir = { version = "2.3.1" }
prost-build = { version = "0.6.1" }
tempdir = "0.3.7"
